export { default as Astro } from "./Astro.icon";
export { default as CSS } from "./CSS.icon";
export { default as CSharp } from "./CSharp.icon";
export { default as Flutter } from "./Flutter.icon";
export { default as HTML } from "./HTML.icon";
export { default as Javascript } from "./Javascript.icon";
export { default as React } from "./React.icon";
export { default as Typescript } from "./Typescript.icon";
export { default as Unity } from "./Unity.icon";
export { default as Vue } from "./Vue.icon";
export { default as Node } from "./Node.icon";
export { default as Java } from "./Java.icon";
export { default as Git } from "./Git.icon";
export { default as Webpack } from "./Webpack.icon";
export { default as Jest } from "./Jest.icon";
export { default as Tailwind } from "./Tailwind.icon";
export { default as SCSS } from "./Sass.icon";
export { default as Qwik } from "./Qwik.icon";
export { default as World } from "./World.icon";
export { default as NextJS} from "./NextJS.icon";
export { default as Mysql} from "./Mysql.icon";